### PR TITLE
Update style to match ONNX.ai page

### PR DESCRIPTION
**Pull request by mitruska**
Update style to match [onnx.ai](onnx.ai) page:
- Changed the color scheme of the scoreboard
- Added navbar header and footer from onnx.ai ([repository](https://github.com/onnx/onnx.github.io))
- Added onnx favicon 

[Live demo](https://mitruska.github.io/scoreboard-test/)

mitruska github io_scoreboard-test_index html (2)

mitruska github io_scoreboard-test_onnxruntime_details_stable html (1)

### CODE REVIEW

**Comment by prasanthpul** [comment]
looks like you also need to regenerate the webpages in the docs folder. or does that happen by some automatic job? if so, is it once a day or more frequent?

**Comment by postrational** [comment]
The page regenerates once a day, so the new version should be up tomorrow automatically.

**Comment by prasanthpul** [comment]
cool. is it done with Github actions? is it also possible to force run it?
would be useful to document it so others know - i didnt find it in the docs

**Comment by mitruska** [comment]
Actually it's configured with Azure pipelines and there is an option to force the update process (for users with permission).
Here is the configuration file [azure-pipelines-website.yml](https://github.com/onnx/backend-scoreboard/blob/master/azure-pipelines-website.yml).
And of course I will add some more details in the dev documentation.

**Pull request merged**
